### ISSUE TITLE
there is no module named Nominatim

### ISSUE THREAD

**Issue by Rishiprogramer** [Amrit-Giri/NumberTracker#1]

**Comment by 4mritGiri** [comment]
Install the module nominating.

`pip install nominatim`

**Comment by Rishiprogramer** [comment]
still is is not

**Comment by 4mritGiri** [comment]
Can you share your issue screen shot

**Comment by Rishiprogramer** [comment]
it is giving wrong location and it has crashed by whole pycharm software. now i have to reinstall it.
